name: food_finder
description: "A new Flutter project."
publish_to: "none"
version: 2.0.0+1
isar_version: &isar_version 3.1.0

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^11.0.0
  google_maps_flutter: ^2.0.10
  location: ^5.0.0
  http: ^0.13.6
  flutter_dotenv: ^5.1.0

  json_annotation: ^4.8.1
  provider: ^6.1.2
  isar:
    version: 3.1.8
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs:
    version: 3.1.8
    hosted: https://pub.isar-community.dev/
  path_provider: ^2.1.2
  uuid: ^4.3.3
  image_picker: ^1.0.7
  path: ^1.8.3
  intl: ^0.19.0
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.7.1
  build_runner: any
  isar_generator:
    version: 3.1.8
    hosted: https://pub.isar-community.dev/

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env